name: ncollapse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pip:
    - torch
    - torchvision
    - foolbox
    - matplotlib
    - tqdm
    - scikit-learn
